# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/9035ccb9-0fe2-462c-aa8c-59206f037b5d";
    fsType = "btrfs";
    options = [
      "subvol=@root"
      "compress=zstd"
      "ssd"
      "noatime"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/9035ccb9-0fe2-462c-aa8c-59206f037b5d";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "compress=zstd"
      "ssd"
      "noatime"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/9035ccb9-0fe2-462c-aa8c-59206f037b5d";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd"
      "ssd"
      "noatime"
    ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/9035ccb9-0fe2-462c-aa8c-59206f037b5d";
    fsType = "btrfs";
    options = [
      "subvol=@log"
      "compress=zstd"
      "ssd"
      "noatime"
    ];
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/9E2D-5874";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
