# This file is autogenerated by the build-plugin script.
{pkgs ? import <nixpkgs> {}}: let
  buildNuPlugin = {
    name,
    version,
    src,
    cargoHash ? null,
    cargoLock ? null,
  }:
    pkgs.rustPlatform.buildRustPackage {
      pname = name;
      inherit version src;

      meta = {
        mainProgram = name;
      };

      cargoHash =
        if cargoLock != null
        then null
        else
          (
            if cargoHash == null
            then "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
            else cargoHash
          );
      cargoLock = cargoLock;

      nativeBuildInputs = [pkgs.python3];

      postPatch = ''
               ${
          if cargoLock != null
          then "cp ${cargoLock.lockFile} Cargo.lock"
          else "rm -f Cargo.lock"
        }

               cat << 'EOF' > patch_cargo.py
               import re
               import os

               if os.path.exists("Cargo.toml"):
                   with open("Cargo.toml", "r") as f:
                       content = f.read()

                   # Match table format [dependencies.nu-plugin]
        version = "..."
                   content = re.sub(
                       r'\[(dependencies|dev-dependencies)\.nu-(plugin|protocol|cmd-base|plugin-test-support)\]\s*\n\s*version\s*=\s*"[^"]+"',
                       r'[\1.nu-\2]\nversion = "0.113.1"',
                       content
                   )

                   # Match inline format nu-plugin = "..." or nu-plugin = { version = "..." }
                   content = re.sub(
                       r'(nu-(plugin|protocol|cmd-base|plugin-test-support))\s*=\s*"[^"]+"',
                       r'\1 = "0.113.1"',
                       content
                   )
                   content = re.sub(
                       r'(nu-(plugin|protocol|cmd-base|plugin-test-support))\s*=\s*\{\s*version\s*=\s*"[^"]+"',
                       r'\1 = { version = "0.113.1"',
                       content
                   )

                   with open("Cargo.toml", "w") as f:
                       f.write(content)
               EOF
               python3 patch_cargo.py
      '';
    };
in {
  nu_plugin_dbus = buildNuPlugin {
    name = "nu_plugin_dbus";
    version = "0.14.0";
    src = pkgs.fetchCrate {
      pname = "nu_plugin_dbus";
      version = "0.14.0";
      sha256 = "0mqi94xmzqkbr338djs4yya6gz3ncqb6fs5sw4w3xh0r73p2c2rn";
    };
    cargoHash = "sha256-V7YfM3ETc3GDl1MyzYKNhmJFOETzNRp6QERH8sw4xic=";
    cargoLock = null;
  };

  nu_plugin_net = buildNuPlugin {
    name = "nu_plugin_net";
    version = "1.10.0";
    src = pkgs.fetchCrate {
      pname = "nu_plugin_net";
      version = "1.10.0";
      sha256 = "14759c1jfxyhrpcjl1lahp6pq3ximjwc9hbwm0bvhzmxy7cj7k5p";
    };
    cargoHash = "sha256-tq0XqY2B7tC2ep8vH6T3nkAqxqhniqzYnhbkfB3SbHU=";
    cargoLock = null;
  };

  nu_plugin_gstat = buildNuPlugin {
    name = "nu_plugin_gstat";
    version = "0.113.1";
    src = pkgs.fetchCrate {
      pname = "nu_plugin_gstat";
      version = "0.113.1";
      sha256 = "1ph5pk6amqlbn9b248smi4iil45ycs1i4mkmfb0xqpczpdza0d6s";
    };
    cargoHash = "sha256-0Sfr0/sfgqnk0lFsKjQQPGFOK30W7Z9iLfWoKGAh/3Q=";
    cargoLock = null;
  };

  nu_plugin_units = buildNuPlugin {
    name = "nu_plugin_units";
    version = "0.1.8";
    src = pkgs.fetchCrate {
      pname = "nu_plugin_units";
      version = "0.1.8";
      sha256 = "14bkk47a11k1krc3j3i7bixw0k4iaja6n3f24n4xvk6fmn77p4fb";
    };
    cargoHash = "sha256-K3hzUmhEjCwhaSuC7MpZbIJGZEKoAzH+LsfK3krm5cU=";
    cargoLock = null;
  };

  nu_plugin_vec = buildNuPlugin {
    name = "nu_plugin_vec";
    version = "1.1.6";
    src = pkgs.fetchCrate {
      pname = "nu_plugin_vec";
      version = "1.1.6";
      sha256 = "0j4wc0m98dja3qc7fjl9vszp9skj8dfz1lip1rmg5yzqjgqwdzxn";
    };
    cargoHash = "sha256-vowe4JuVoS8DQHj6mZGqw2F8rpdjLDAyKzH0SlSuFCY=";
    cargoLock = null;
  };

  nu_plugin_ws = buildNuPlugin {
    name = "nu_plugin_ws";
    version = "1.0.6";
    src = pkgs.fetchCrate {
      pname = "nu_plugin_ws";
      version = "1.0.6";
      sha256 = "077ip1q087qvzxbl39q1x1p256k6pxylky872sfnmk8cjz4qv9df";
    };
    cargoHash = "sha256-VwEkQbKDh0Av+S3xDC5awuGolSn2Zqr73ipIMb2AxgI=";
    cargoLock = null;
  };

  nu_plugin_x509 = buildNuPlugin {
    name = "nu_plugin_x509";
    version = "0.1.8";
    src = pkgs.fetchCrate {
      pname = "nu_plugin_x509";
      version = "0.1.8";
      sha256 = "1dpysfizry9wmlcd8fix81was9hb6dip528x8i0zyi6r656ni1k8";
    };
    cargoHash = "sha256-mt3TGAk77TiCAANIX2YpyAOJO0FF1Fty9ela+zaB7yM=";
    cargoLock = null;
  };

  nu_plugin_regex = buildNuPlugin {
    name = "nu_plugin_regex";
    version = "0.22.0";
    src = pkgs.fetchCrate {
      pname = "nu_plugin_regex";
      version = "0.22.0";
      sha256 = "1lbkzrcdpvq8qij9235bm039wpd7aqab2a60cik7m6zwi6sa5x4c";
    };
    cargoHash = "sha256-Y5DxLHKgT1M8dYOTRtYjU07XF36zN0S6STMZUGCpFc4=";
    cargoLock = null;
  };

  nu_plugin_terminal_qr = buildNuPlugin {
    name = "nu_plugin_terminal_qr";
    version = "1.1.1";
    src = pkgs.fetchCrate {
      pname = "nu_plugin_terminal_qr";
      version = "1.1.1";
      sha256 = "1i54i4y9n2xllyvnwhhij9g0282yfib7kfnb8rm27p2m75gs3vd5";
    };
    cargoHash = "sha256-fjTAOqJwkroEK+rkDNKOtcYvoRBU0mKZ4FRchzArFrc=";
    cargoLock = null;
  };

  nu_plugin_plotters = buildNuPlugin {
    name = "nu_plugin_plotters";
    version = "0.2.5+0.111.0";
    src = pkgs.fetchCrate {
      pname = "nu_plugin_plotters";
      version = "0.2.5+0.111.0";
      sha256 = "03jrgjgbpznzvmbpv1dhv1m490hgggwlpl3cx5sgzj9aj471jkmp";
    };
    cargoHash = "sha256-GMcM5q5DvLkiHthfrx9CBFFdl+hScAUXSeRx1m14q+c=";
    cargoLock = null;
  };

  nu_plugin_json_path = buildNuPlugin {
    name = "nu_plugin_json_path";
    version = "0.23.0";
    src = pkgs.fetchCrate {
      pname = "nu_plugin_json_path";
      version = "0.23.0";
      sha256 = "03gh7zpznm5aims2fh6y3ghs4k43wd2h6yg8s49cy29w4r65mysj";
    };
    cargoHash = "sha256-IsfTkow9OyOGiYbqrt/gl+O2awq1ZVm0GbyNOaeh1cQ=";
    cargoLock = null;
  };

  nu_plugin_hashes = buildNuPlugin {
    name = "nu_plugin_hashes";
    version = "0.1.9";
    src = pkgs.fetchCrate {
      pname = "nu_plugin_hashes";
      version = "0.1.9";
      sha256 = "1hc0lm61hwa9k90hjmajq46dx6dxp95s76mnq0ga8kydgr0fmbwi";
    };
    cargoHash = "sha256-lDi53pvRPL9wrc+mhCbSfFMXeA4JQ/O4D35at3rXssU=";
    cargoLock = null;
  };

  nu_plugin_dns = buildNuPlugin {
    name = "nu_plugin_dns";
    version = "4.0.10";
    src = pkgs.fetchCrate {
      pname = "nu_plugin_dns";
      version = "4.0.10";
      sha256 = "1acpm3a7ri2smr7nq3cp8kbpgabhrmyf5pi14dkyycdaaxnsjd64";
    };
    cargoHash = "sha256-hoI7A29cVSTMYjMu56SjADnvkLH/NjdQVN4GeuRmI6Q=";
    cargoLock = null;
  };

  nu_plugin_format_pcap = buildNuPlugin {
    name = "nu_plugin_format_pcap";
    version = "0.1.0";
    src = pkgs.fetchFromGitHub {
      owner = "b4nst";
      repo = "nu_plugin_format_pcap";
      rev = "d73262165556c33e3f051ec7b1c542e445c74ff5";
      sha256 = "1q4avi0pss8rdss37gwmcqlb48c9f79i3xh6li51y3plxs4k3lrx";
    };
    cargoHash = null;
    cargoLock = {
      lockFile = ./format_pcap_Cargo.lock;
    };
  };
}
